name: run mavbot

on:
  # push: # Debugging
  #   branches:
  #     - main
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants write permission
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false
    steps:

      - name: Checkout repository content
        uses: actions/checkout@v3 # Checkout the repository content to GitHub runner

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Install the required Python version
      
      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry # Cache directory used by Poetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies with Poetry
        run: poetry install

      - name: Execute Python script
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: poetry run python main.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Add GH_TOKEN to your repository secrets
          branch: main
